// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKangXmTkLjO6CnMfe1yAv4O7koDWmzU',
    appId: '1:549383268423:web:b1d4a4d7e62bb5c121a962',
    messagingSenderId: '549383268423',
    projectId: 'final-exam-45545',
    authDomain: 'final-exam-45545.firebaseapp.com',
    storageBucket: 'final-exam-45545.appspot.com',
    measurementId: 'G-QWC62VS5HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHzG4pz7JXKkAYpN-fKsIV_HGhuixbjkw',
    appId: '1:549383268423:android:cbb111123d60aa3d21a962',
    messagingSenderId: '549383268423',
    projectId: 'final-exam-45545',
    storageBucket: 'final-exam-45545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCbuDPbuOP3Qe9vNtTZvM1evBaEsb7TVU',
    appId: '1:549383268423:ios:e673dc6f0177d0cc21a962',
    messagingSenderId: '549383268423',
    projectId: 'final-exam-45545',
    storageBucket: 'final-exam-45545.appspot.com',
    iosBundleId: 'com.example.finalExamFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCbuDPbuOP3Qe9vNtTZvM1evBaEsb7TVU',
    appId: '1:549383268423:ios:e673dc6f0177d0cc21a962',
    messagingSenderId: '549383268423',
    projectId: 'final-exam-45545',
    storageBucket: 'final-exam-45545.appspot.com',
    iosBundleId: 'com.example.finalExamFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEKangXmTkLjO6CnMfe1yAv4O7koDWmzU',
    appId: '1:549383268423:web:c20aca144d60ffad21a962',
    messagingSenderId: '549383268423',
    projectId: 'final-exam-45545',
    authDomain: 'final-exam-45545.firebaseapp.com',
    storageBucket: 'final-exam-45545.appspot.com',
    measurementId: 'G-RPRYN9H806',
  );
}
